#!/bin/bash

# This script starts a simple server to display our front end and
# spawns the c server in the background. This does not recompile

cd ascgif/src/
./server &
cd ../site/
python -m SimpleHTTPServer
