#!/bin/bash

# This script starts a simple server to display our front end, then
# builds and runs our c server (in the background) to actually process
# the images and serve up the content via AJAX

export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig
cd ascgif/src/
make
./server &
cd ../site/
python -m SimpleHTTPServer
